### PR TITLE
Add synchronize strategy

### PR DESCRIPTION
**Pull request by gfaivre**

### CODE REVIEW

**Comment by hyvs** [comment]
I should avoid to rename `strategy` -> `strategies` , variables naming follow this convention : 
`manala_deploy_strategy_git_head`:
- `manala` : org
- `deploy` : role
- `strategy_git`:  task

We should renamed `manala_deploy_strategy_git_head` to `manala_deploy_strategies_git_head` (BC)

**Comment by gfaivre** [comment]
Ok for the BC, but I think it's disturbing to have several deployment strategies under a directory named "strategy".
Should I revert it for now ?

**Comment by hyvs** [comment]
+1 to revert, @nervo ?

**Comment by nervo** [comment]
Same here :)

**Comment by gfaivre** [comment]
Revert it. However, I still believe this naming is confusing.

**Comment by hyvs** [comment]
LGTM 👍

**Review by hyvs — APPROVED** [review]

**Pull request merged**
