### PR TITLE
Handle symfony assets version in dedicated config file

### PR DESCRIPTION
**Pull request by hyvs**

### CODE REVIEW

**Comment by nervo** [comment]
Why not using ansible release name instead of git tag ?

/ping @hyvs

**Comment by hyvs** [comment]
> Why not using ansible release name instead of git tag ?

Should be an option, maybe another MR.

**Comment by hyvs** [comment]
ok @nervo done here, see https://github.com/manala/ansible-role-deploy/pull/18/commits/c7f009d60c8dc87240f3526378664783d8a31bbc

**Pull request merged**
